// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UltraNuke.Barasingha.AlarmManagement.Infrastructure;

namespace UltraNuke.Barasingha.AlarmManagement.API.Migrations
{
    [DbContext(typeof(AlarmManagementContext))]
    [Migration("20210728091344_v002")]
    partial class v002
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("UltraNuke.Barasingha.AlarmManagement.Domain.AggregatesModel.Alarm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClaimMethod")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClaimTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ClaimUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClaimUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CloseMethod")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CloseUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CloseUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Handling")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurrenceTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LevelId");

                    b.ToTable("AM_Alarm");
                });

            modelBuilder.Entity("UltraNuke.Barasingha.AlarmManagement.Domain.AggregatesModel.AlarmEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlarmId");

                    b.ToTable("AM_AlarmEvidence");
                });

            modelBuilder.Entity("UltraNuke.Barasingha.AlarmManagement.Domain.AggregatesModel.AlarmWaitingStaff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlarmId");

                    b.ToTable("AM_AlarmWaitingStaff");
                });

            modelBuilder.Entity("UltraNuke.Barasingha.AlarmManagement.Domain.AggregatesModel.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("No")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AM_Category");
                });

            modelBuilder.Entity("UltraNuke.Barasingha.AlarmManagement.Domain.AggregatesModel.Dispatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("No")
                        .HasColumnType("int");

                    b.Property<int>("WaitTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AM_Dispatch");
                });

            modelBuilder.Entity("UltraNuke.Barasingha.AlarmManagement.Domain.AggregatesModel.DispatchCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlarmDispatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ConditionAndOr")
                        .HasColumnType("int");

                    b.Property<int>("ConditionField")
                        .HasColumnType("int");

                    b.Property<int>("ConditionLogical")
                        .HasColumnType("int");

                    b.Property<string>("ConditionValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("No")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlarmDispatchId");

                    b.ToTable("AM_DispatchCondition");
                });

            modelBuilder.Entity("UltraNuke.Barasingha.AlarmManagement.Domain.AggregatesModel.DispatchUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlarmDispatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Immediately")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlarmDispatchId");

                    b.ToTable("AM_DispatchUser");
                });

            modelBuilder.Entity("UltraNuke.Barasingha.AlarmManagement.Domain.AggregatesModel.Level", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("No")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AM_Level");
                });

            modelBuilder.Entity("UltraNuke.Barasingha.AlarmManagement.Domain.AggregatesModel.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("No")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AM_Notification");
                });

            modelBuilder.Entity("UltraNuke.Barasingha.AlarmManagement.Domain.AggregatesModel.NotificationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AlarmState")
                        .HasColumnType("int");

                    b.Property<int>("DelayStrategy")
                        .HasColumnType("int");

                    b.Property<Guid?>("LevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NotificationMode")
                        .HasColumnType("int");

                    b.Property<int>("NotificationTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("NotificationId");

                    b.ToTable("AM_NotificationItem");
                });

            modelBuilder.Entity("UltraNuke.Barasingha.AlarmManagement.Domain.AggregatesModel.Alarm", b =>
                {
                    b.HasOne("UltraNuke.Barasingha.AlarmManagement.Domain.AggregatesModel.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("UltraNuke.Barasingha.AlarmManagement.Domain.AggregatesModel.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId");

                    b.Navigation("Category");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("UltraNuke.Barasingha.AlarmManagement.Domain.AggregatesModel.AlarmEvidence", b =>
                {
                    b.HasOne("UltraNuke.Barasingha.AlarmManagement.Domain.AggregatesModel.Alarm", "Alarm")
                        .WithMany("Evidences")
                        .HasForeignKey("AlarmId");

                    b.Navigation("Alarm");
                });

            modelBuilder.Entity("UltraNuke.Barasingha.AlarmManagement.Domain.AggregatesModel.AlarmWaitingStaff", b =>
                {
                    b.HasOne("UltraNuke.Barasingha.AlarmManagement.Domain.AggregatesModel.Alarm", "Alarm")
                        .WithMany("WaitingStaffs")
                        .HasForeignKey("AlarmId");

                    b.Navigation("Alarm");
                });

            modelBuilder.Entity("UltraNuke.Barasingha.AlarmManagement.Domain.AggregatesModel.DispatchCondition", b =>
                {
                    b.HasOne("UltraNuke.Barasingha.AlarmManagement.Domain.AggregatesModel.Dispatch", "AlarmDispatch")
                        .WithMany("DispatchConditions")
                        .HasForeignKey("AlarmDispatchId");

                    b.Navigation("AlarmDispatch");
                });

            modelBuilder.Entity("UltraNuke.Barasingha.AlarmManagement.Domain.AggregatesModel.DispatchUser", b =>
                {
                    b.HasOne("UltraNuke.Barasingha.AlarmManagement.Domain.AggregatesModel.Dispatch", "AlarmDispatch")
                        .WithMany("DispatchUsers")
                        .HasForeignKey("AlarmDispatchId");

                    b.Navigation("AlarmDispatch");
                });

            modelBuilder.Entity("UltraNuke.Barasingha.AlarmManagement.Domain.AggregatesModel.NotificationItem", b =>
                {
                    b.HasOne("UltraNuke.Barasingha.AlarmManagement.Domain.AggregatesModel.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId");

                    b.HasOne("UltraNuke.Barasingha.AlarmManagement.Domain.AggregatesModel.Notification", "Notification")
                        .WithMany("NotificationItems")
                        .HasForeignKey("NotificationId");

                    b.Navigation("Level");

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("UltraNuke.Barasingha.AlarmManagement.Domain.AggregatesModel.Alarm", b =>
                {
                    b.Navigation("Evidences");

                    b.Navigation("WaitingStaffs");
                });

            modelBuilder.Entity("UltraNuke.Barasingha.AlarmManagement.Domain.AggregatesModel.Dispatch", b =>
                {
                    b.Navigation("DispatchConditions");

                    b.Navigation("DispatchUsers");
                });

            modelBuilder.Entity("UltraNuke.Barasingha.AlarmManagement.Domain.AggregatesModel.Notification", b =>
                {
                    b.Navigation("NotificationItems");
                });
#pragma warning restore 612, 618
        }
    }
}
